### ISSUE TITLE
Cargo install's --git flag: "member of the wrong workspace"

### ISSUE THREAD

**Issue by dtolnay** [facebookincubator/buck2#36]
Normally `cargo install` is able to install binaries from a subdirectory of a git repo. It will find all workspace roots, resolve the requested package name in each one, fail if there is an ambiguity, and otherwise install it.

In buck2's case it seems to go wrong because **2 different workspaces** both claim to contain some of the same crates.

```console
$ cargo install cli --git https://github.com/facebookincubator/buck2 --bin buck2
    Updating git repository `https://github.com/facebookincubator/buck2`
error: package `/home/david/.cargo/git/checkouts/buck2-4c0ac0340bde8e6a/c117530/allocative/allocative/Cargo.toml` is a member of the wrong workspace
expected: /home/david/.cargo/git/checkouts/buck2-4c0ac0340bde8e6a/c117530/Cargo.toml
actual:   /home/david/.cargo/git/checkouts/buck2-4c0ac0340bde8e6a/c117530/allocative/Cargo.toml
```

https://github.com/facebookincubator/buck2/blob/c117530548ddc3ec1e85b5af52e5fe678b32dff0/Cargo.toml#L3-L7

https://github.com/facebookincubator/buck2/blob/c117530548ddc3ec1e85b5af52e5fe678b32dff0/allocative/Cargo.toml#L1-L5

It's hard for me to tell whether this arrangement is intentional, or just an oversight. In any case, it leads to issues.

**Comment by stepancheg** [comment]
I'll move it.

**Comment by stepancheg** [comment]
Must be fixed now.
