### ISSUE TITLE
Refer to external dependencies?

### ISSUE THREAD

**Issue by teh** [facebookincubator/buck2#51]
I'm trying to import

```
prebuilt_cxx_library(
    name = "spdlog",
    header_dirs = ["/nix/store/yjqxa9782hpl59cg17h5ma4d4l0zh0ac-spdlog-1.10.0-dev/include/"],
    exported_headers = glob(["**/*.h"]),
    header_only = True,
    visibility = ["PUBLIC"],
)
```

I get `Error when treated as a path: expected a relative path but got an absolute path instead:`

I also tried using a relative path like `../../../nix/store/...`  which worked in buck1 IIRC but get

      Error when treated as a target: Invalid absolute target pattern `../../../../nix/store/yjqxa9782hpl59cg17h5ma4d4l0zh0ac-spdlog-1.10.0-dev/include/` is not allowed: Expected a `:`, a trailing `/...` or the literal `...`.
      Error when treated as a path: expected a normalized path but got an un-normalized path instead: `../../../../nix/store/yjqxa9782hpl59cg17h5ma4d4l0zh0ac-

Is there a recommended way to include external dependencies?

**Comment by ndmitchell** [comment]
One way that should work is to create a symlink adjacent to your target file that points out to the Nix store.

**Comment by teh** [comment]
thank!!!!
