### ISSUE TITLE
It should be possible to override protoc-bin-vendored

### ISSUE THREAD

**Issue by thoughtpolice** [facebookincubator/buck2#65]
As of #60, buck2 no longer depends on an external `protoc` binary, but uses a binary vendored from @stepancheg's [rust-protoc-bin-vendored](https://github.com/stepancheg/rust-protoc-bin-vendored/).

While reducing friction is a noble goal I support fully, this had an unintended side effect: it breaks the ability to build buck using tools like [Nix](https://nixos.org), without tiny workarounds

## Problem: dynamically linked binaries require `/usr/lib`

The basic problem is that when you build something with Nix, paths like `/usr` are not available during the build process. Every dependency must be declared specifically, and all dependencies are located within `/nix/store`. This includes `libc.so.6`, in fact, pthreads, and everything else.

```
austin@GANON:~/src/rust-protoc-bin-vendored$ ldd protoc-bin-vendored-linux-x86_64/bin/protoc
        linux-vdso.so.1 (0x00007ffcf97b1000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f53ce17d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f53ce096000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f53cde6e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f53ce18d000)
```

This means that this ELF binary *requires* `/lib64/ld-linux-x86-64.so.2` to be available, but it won't be available during the build phase. Therefore during the buck2 build process, when attempting to invoke `protoc`, it will fail, because the binary cannot have its dependencies satsified by the dynamic system linker `ld.so`. Here's what the Nix-ified output looks like:

```
a@link:~/src/rust-protoc-bin-vendored/ > ldd protoc-bin-vendored-linux-x86_64/bin/protoc
        linux-vdso.so.1 (0x00007ffeaf4ab000)
        libpthread.so.0 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libpthread.so.0 (0x00007f04dc75f000)
        libm.so.6 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libm.so.6 (0x00007f04dc67f000)
        libc.so.6 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libc.so.6 (0x00007f04dc400000)
        /lib64/ld-linux-x86-64.so.2 => /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib64/ld-linux-x86-64.so.2 (0x00007f04dc766000)
```

## Can't we fix the binaries?

There is a fun tool called [patchelf](https://github.com/NixOS/patchelf) that *could* fix this for us, and is designed to handle this exact problem for Nix machines; you can just `patchelf` binaries to get them to work. And the binaries would work if we could just patch the `libc.so.6` paths. However it would require us to inject patchelf into the `cargo` build process for buck, so it's not exactly trivial, and looked quite painful for me to pull off reliably.

> The binaries could also be statically linked, but I don't know how much of a PITA that is.

## Quick fix patch

The easiest fix I found was just to set `PROTOC` and `PROTOC_INCLUDE` manually in the build environment to point to my working copies of the compiler and its include code, and then just comment out the code that uses `protoc-bin-vendored`

The following patch was sufficient for me to keep working as if nothing happened:

```diff
commit e92d67e4568c5fa6bcfbbd7ee6e16b9f132114a9
Author: Austin Seipp <aseipp@pobox.com>
Date:   Mon Jan 2 00:46:31 2023 -0600

    hack(protoc): do not use protoc-bin-vendored
    
    This package doesn't work under the Nix sandbox when using Cargo,
    because the vendored binaries can't easily be patchelf'd to look at the
    correct libc paths.
    
    Instead, just rely on PROTOC and PROTOC_INCLUDE being set manually.
    
    Signed-off-by: Austin Seipp <aseipp@pobox.com>

diff --git a/app/buck2_protoc_dev/src/lib.rs b/app/buck2_protoc_dev/src/lib.rs
index 69980b9a..fecdde46 100644
--- a/app/buck2_protoc_dev/src/lib.rs
+++ b/app/buck2_protoc_dev/src/lib.rs
@@ -80,8 +80,8 @@ impl Builder {
 
     pub fn setup_protoc(self) -> Self {
         // It would be great if there were on the config rather than an env variables...
-        maybe_set_protoc();
-        maybe_set_protoc_include();
+        //maybe_set_protoc();
+        //maybe_set_protoc_include();
         self
     }
```

This is small enough that I'm happy to carry it for now, but a solution to support both would be nice, with vendoring being the default.

**Comment by ndmitchell** [comment]
I think having all Nix users forced to carry a patch would be very sad, so definitely don't want to do that.

In a previous incantation, if PROTOC or PROTOC_INCLUDE were already set, we left them alone and didn't change them. That would be one thing to do, Thoughts @stepancheg ?

I also wonder if on Nix the protoc_bin_vendored should return an Err? Or maybe that's too hard to detect reliably.

**Comment by thoughtpolice** [comment]
Detecting when Nix is being used is probably not easy or reliable (well, you could just ask if `/usr` exists, which is a pretty good, but...)

It might also be worth just making the usage of `protoc-bin-vendored` a feature in the Cargo file, that can be disabled or enabled, I think? That way you have to opt into it pretty explicitly without just setting some magic environment variables that are ambient and not easily discoverable.

Please note that I have not tried to self-bootstrap buck2 with buck2 (I don't know if that will be the "recommended" way to build production binaries in the long run, once remote execution and caching are in place, for example) so I don't know if this might be impacted, but from reading previous commit messages, I think y'all have that already handled regardless.

**Comment by stepancheg** [comment]
> PROTOC or PROTOC_INCLUDE were already set, we left them alone and didn't change them. That would be one thing to do

Should be OK, if we rename them to `BUCK2_PROTOC` and `BUCK2_PROTOC_INCLUDE` to avoid accidentally reading environment variables we are not supposed to.

> on Nix the protoc_bin_vendored should return an Err? Or maybe that's too hard to detect reliably.

It is not the job of the crate to do it. It just returns the binary packed in the crate, that's it.

> patchelf

Patchelf seems to be too hard to do reliably (because if has to do it inside the dependency crate).

Some people in the internet suggest using [nix-ld](https://github.com/Mic92/nix-ld). Can't it be used? I cannot understand it from the page description.

**Comment by ndmitchell** [comment]
My view is that working out the box is a good thing, so that means having protoc-bin-vendored be default is good, as it will reduce a lot of friction for Windows/Ubuntu users. Having that overridable by environment variables also sounds good (not too fussed on their names). Detecting Nix, running patchelf or a custom nix-ld all seem to go against the Nix philosophy, so seem less desirable.

@thoughtpolice are you installing Buck2 by writing a Nix derivation? If we included that Nix derivation in the root of the repo, would that make it easy in Nix world?

**Comment by thoughtpolice** [comment]
> Some people in the internet suggest using [nix-ld](https://github.com/Mic92/nix-ld). Can't it be used? I cannot understand it from the page description.

`nix-ld` is clever but inappropriate. The assumption behind it is that you are running NixOS, and thus a path like `/usr/lib` does not exist. It then mounts a fake FUSE filesystem onto these paths, and intercepts calls for `.so` libraries. So, for one, it requires a FUSE daemon to exist, so that the filesystem can translate paths like `/lib64/ld-linux-x86-64.so.2` into a different path in the `/nix/store`. And, this assumes you're running NixOS, but to be clear I am not; I am using normal Ubuntu Linux, with Nix (the package manager) installed on top of it. I *do* actually have a real `/lib64/ld-linux-x86-64.so.2` on my system. So why is this all a problem?

This is because when you tell Nix to build something, it creates a hermetically sealed filesystem namespace under a different (random) Unix user, then runs the build process (e.g. `cargo build`) inside of it. It does all builds under these sealed namespaces, and they have a highly restricted view of the filesystem, in fact it isn't even possible to see any other `/nix/store` paths than ones you've declared as dependencies! This sealed namespace, where the build takes place, does NOT allow any other filesystems, network access, or anything else to be mounted inside the build.

To be fair I should have been more clear about this second requirement, where the build takes place, but this same basic problem applies to NixOS too, not just the "Nix Build Environment." Any reliance on ambient paths like `/usr/lib` is inevitably destined to fail and need a workaround for these cases.

**Comment by thoughtpolice** [comment]
> @thoughtpolice are you installing Buck2 by writing a Nix derivation? If we included that Nix derivation in the root of the repo, would that make it easy in Nix world?

Yes, this Nix derivation is here. There are one or two ugly hacks inside of it, but otherwise it is able to be built like (almost!) any other Rust program in Nixpkgs (which is the big library of Nix code that contains the set of things that Nix, the package manager, can install for you): https://github.com/thoughtpolice/buck2-nix/blob/main/buck/nix/buck2/default.nix

It would make it *somewhat* easier, but I hesitate to just add it, because:

- A normal Nix expression isn't enough in this case; we would likely want Buck to have its own "Nix Flake". Flakes are sort of an abstraction on top of Nix, but they allow some fun features.
- It would need to be CI'd in order to stop regressions
  - But that means it would be very annoying for non-Nix users to fix failures
  - Nix is not really an easy tool to debug if you haven't used it
  - e.g. the protoc-vendored patch would have been completely held up on it
- But most of all, we will need a working `Cargo.lock` file in order for Nix to build buck2.
  - This is effectively a must-have requirement.
  - Right now, I have a shell script that updates the `buck2` Nix expression, and every time it does this, it re-generates `Cargo.lock` and includes it.
  - My understanding is that Meta does not use lockfiles for its Rust projects, precisely because there is already a globally consistent view of all Rust dependencies inside your main repository (thanks to vendoring things and letting Buck itself drive the build). Therefore there is no need, because when you write `needed-foo-dep = "0.8"`, there is no ambiguity about what it refers to (e.g. 0.8.1, 0.8.2, etc) &mdash; it refers exactly to the version of `needed-foo-dep` inside the repository itself.

At the moment, I'd be happy to contribute one, but at the pace buck2 is moving before its stabilization I'm not sure if y'all want all these burdens. And the lockfile one is absolutely mandatory, but also seems to affect other projects like Sapling, where Nix developers have had to generate our own lockfiles and include them. So I don't know what the policy should be here.

That said &mdash; I find Nix to be wonderful to adopt in some sense, for projects like this, because I find it helps encourage codebases to follow best open source practices; when in Rome, do as the Romans. So even if it slows you down sometimes, it may help "keep you honest" e.g. you can't pull hacks like "oh I'm going to download something over the internet during the build", you have to explicitly declare all your needed deps, stuff like that.

I'd be happy to think about writing and helping maintain an upstream Nix derivation, but maybe it would be easier to hash out over a video call or something. Unfortunately I'm incredibly busy at least until Saturday, at this rate, so it would probably have to wait for Monday or Tuesday. Maybe something to think about!

**Comment by stepancheg** [comment]
I'll restore env vars.

**Comment by stepancheg** [comment]
Committed. Closing the issue. Please reopen if this does not work as expected.
